version: "3.1"

services:
  db:
    container_name: clubify
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5555:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
